from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class ApprovalReasonKind(StrEnum):
    """Closed set of approval trigger reasons."""

    NONE = "none"
    HUMAN_INTERACTION = "human_interaction"
    SENSITIVE_RESOURCE = "sensitive_resource"
    UNAUTHORIZED_PATH = "unauthorized_path"
    ELEVATED_COMMAND = "elevated_command"
    POLICY_RULE = "policy_rule"


class RiskLevel(StrEnum):
    """Risk levels for operations requiring consent."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass(frozen=True)
class ApprovalRequirement:
    """Structured authorization & consent requirement generated by control plane."""

    required: bool = False
    reason_kind: ApprovalReasonKind = ApprovalReasonKind.NONE
    risk_level: RiskLevel = RiskLevel.LOW
    summary: str = ""
    target_resource: str | None = None
    details: Mapping[str, Any] = field(default_factory=dict)
