"""Cognition-plane model contracts."""

from lca.contracts.models.cognition.prompt_assembly import (
    BrainPromptCatalog,
    MissingPromptSectionError,
    MissingSectionKindError,
    PromptAssembler,
    PromptSectionRegistry,
    PromptTemplate,
    PromptTemplateConfig,
    PromptTemplateProvider,
    PromptTemplateSelector,
    PromptTemplateVariant,
    PromptTrace,
    PureSection,
    SectionKind,
    SectionManifest,
    SectionOutput,
    SectionReference,
    SectionTrace,
    SelectorDecisionPath,
    StatefulSection,
    normalize_assembler_result,
    normalize_selector_result,
)
from lca.contracts.models.cognition.task import (
    Reflection,
    TaskEntry,
    TaskId,
    TaskList,
    TaskStatus,
)
from lca.contracts.models.cognition.tool_defer import DeferMode, ToolNamespace

__all__ = [
    "BrainPromptCatalog",
    "DeferMode",
    "MissingPromptSectionError",
    "MissingSectionKindError",
    "PromptAssembler",
    "PromptSectionRegistry",
    "PromptTemplate",
    "PromptTemplateConfig",
    "PromptTemplateProvider",
    "PromptTemplateSelector",
    "PromptTemplateVariant",
    "PromptTrace",
    "PureSection",
    "Reflection",
    "SectionKind",
    "SectionManifest",
    "SectionOutput",
    "SectionReference",
    "SectionTrace",
    "SelectorDecisionPath",
    "StatefulSection",
    "TaskEntry",
    "TaskId",
    "TaskList",
    "TaskStatus",
    "ToolNamespace",
    "normalize_assembler_result",
    "normalize_selector_result",
]
