"""Generate [tool.importlinter.contracts] for pyproject.toml.

Adds:
- Per-package forbidden rules (lca.contracts.* and lca.plugins.* cannot import specific
  implementation details)
- Independence rule for lca.plugins.* sub-packages
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
PYPROJECT = ROOT / "pyproject.toml"

# (source_module, forbidden_modules_list) pairs
# NOTE: 当前包名为 layer*/harness/plugins/contracts/gateway；Phase 2 会切换为语义名
# Phase 1 范围内只加不与现状冲突的规则；过严的规则（lca.cognition 不依赖 lca.runtime 等）
# 待后续 Phase 治理。
PACKAGE_FORBIDDEN_RULES: list[tuple[str, list[str]]] = [
    # lca.contracts sub-packages 禁依赖具体 lca.infrastructure 子包
    # （已有"contracts 不得依赖任何实现"基础规则；这里进一步收紧到具体子包）
    ("lca.contracts.atoms", ["lca.infrastructure.llm", "lca.infrastructure.tools", "lca.infrastructure.sandbox"]),
    ("lca.contracts.models", ["lca.infrastructure.llm", "lca.infrastructure.tools", "lca.infrastructure.state_store"]),
    ("lca.contracts.models.core", ["lca.infrastructure.llm", "lca.infrastructure.tools"]),
    ("lca.contracts.models.observability", ["lca.infrastructure.llm", "lca.infrastructure.cli"]),
    ("lca.contracts.models.team", ["lca.infrastructure.llm", "lca.infrastructure.tools"]),
    ("lca.contracts.observability", ["lca.infrastructure.llm", "lca.infrastructure.tools", "lca.infrastructure.cli"]),
    ("lca.contracts.observability.schemas", ["lca.infrastructure.llm", "lca.infrastructure.tools"]),
    ("lca.contracts.protocols", ["lca.infrastructure.llm", "lca.infrastructure.tools", "lca.infrastructure.sandbox"]),
    ("lca.contracts.mechanisms", ["lca.infrastructure.llm", "lca.infrastructure.tools"]),
    ("lca.contracts.harness", ["lca.infrastructure.llm", "lca.infrastructure.tools"]),
    # Phase 2 之后再加 cognition/runtime/agent 反向依赖规则
]

# lca.plugins sub-packages 互不依赖
# NOTE: Phase 1 暂不启用此规则。原因：lca.plugins.providers 是多个 plugin 的
# 间接依赖中枢（通过 lca.infrastructure.observability.journal.journal_io），导致
# 几乎所有 lca.plugins 子包都间接依赖 providers，独立性规则会全失败。
# 计划在 Phase 2/3 治理 providers 依赖后重新启用。
LCA_PLUGINS_INDEPENDENCE: list[str] = []  # 暂空


def toml_list(items: list[str]) -> str:
    if not items:
        return "[]"
    inner = ",\n    ".join(f'"{x}"' for x in items)
    return f"[\n    {inner},\n]"


def generate_rules() -> str:
    lines = []
    for source, forbidden in PACKAGE_FORBIDDEN_RULES:
        lines.append(f'''[[tool.importlinter.contracts]]
name = "Per-package forbidden: {source}"
type = "forbidden"
source_modules = ["{source}"]
forbidden_modules = {toml_list(forbidden)}
''')
    lines.append(f'''[[tool.importlinter.contracts]]
name = "lca.plugins 子包互不依赖"
type = "independence"
modules = {toml_list(LCA_PLUGINS_INDEPENDENCE)}
''')
    return "\n".join(lines)


def main() -> int:
    existing = PYPROJECT.read_text(encoding="utf-8")

    # Remove old per-package forbidden / independence rules
    new_content = re.sub(
        r"# === PER-PACKAGE FORBIDDEN RULES.*?# === END PER-PACKAGE ===\n*",
        "",
        existing,
        flags=re.DOTALL,
    )

    # Insert new rules before the last [tool.*] section
    rules = generate_rules()
    marker = "# === PER-PACKAGE FORBIDDEN RULES (auto-generated by scaffold_importlinter_rules.py) ==="
    end_marker = "# === END PER-PACKAGE ==="

    if marker in new_content:
        new_content = re.sub(
            rf"{re.escape(marker)}.*?{re.escape(end_marker)}",
            f"{marker}\n{rules}{end_marker}",
            new_content,
            flags=re.DOTALL,
        )
    else:
        # Append at end
        new_content = new_content.rstrip() + f"\n\n{marker}\n{rules}{end_marker}\n"

    PYPROJECT.write_text(new_content, encoding="utf-8")
    print(f"wrote {len(PACKAGE_FORBIDDEN_RULES)} forbidden + 1 independence rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
