"""Generate TypeScript literal from a RenderContract registry."""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from lca.infrastructure.tools.contract.render import FieldSpec, RenderContract


_HEADER = """\
// generated by lca/infrastructure/tools/contract/codegen_ts.py — do not edit
export interface ToolField {
  readonly pythonKey: string;
  readonly wireKey: string;
  readonly kind: 'string' | 'int' | 'bool' | 'json' | 'file_ref' | 'content_ref';
  readonly source: 'argument' | 'observation' | 'evidence_ref' | 'constant';
  readonly required: boolean;
}
export interface ToolRenderContract {
  readonly toolName: string;
  readonly identifier: string;
  readonly apiName: string;
  readonly args: readonly ToolField[];
  readonly state: readonly ToolField[];
  readonly streaming: readonly ToolField[];
  readonly contentField: string | null;
  readonly waitFor: readonly string[];
}"""


def _ts_field(field: FieldSpec, indent: int) -> str:
    """Render a single ToolField as a TS object literal."""
    pad = " " * indent
    return (
        f"{pad}{{ pythonKey: {json.dumps(field.python_key)}, "
        f"wireKey: {json.dumps(field.wire_key)}, "
        f"kind: {json.dumps(field.kind)}, "
        f"source: {json.dumps(field.source)}, "
        f"required: {'true' if field.required else 'false'} }}"
    )


def _ts_field_list(
    fields: tuple[FieldSpec, ...], indent: int, item_indent: int | None = None
) -> str:
    """Render a tuple[FieldSpec, ...] as a TS array literal."""
    if not fields:
        return "[]"
    if item_indent is None:
        item_indent = indent + 2
    pad = " " * indent
    items = ",\n".join(_ts_field(f, item_indent) for f in fields)
    return f"[\n{items},\n{pad}]"


def _ts_string_tuple(values: tuple[str, ...]) -> str:
    """Render a tuple[str, ...] as a TS array literal."""
    if not values:
        return "[]"
    items = ", ".join(json.dumps(v) for v in values)
    return f"[{items}]"


def _ts_contract_entry(name: str, c: RenderContract, indent: int) -> str:
    """Render a single registry entry."""
    pad = " " * indent
    inner = " " * (indent + 2)
    args = _ts_field_list(c.args, indent + 2)
    state = _ts_field_list(c.state, indent + 2)
    streaming = _ts_field_list(c.streaming, indent + 2)
    cf = "null" if c.content_field is None else json.dumps(c.content_field)
    wf = _ts_string_tuple(c.wait_for)
    return (
        f"{pad}{json.dumps(name)}: {{\n"
        f"{inner}toolName: {json.dumps(c.tool_name)},\n"
        f"{inner}identifier: {json.dumps(c.identifier)},\n"
        f"{inner}apiName: {json.dumps(c.api_name)},\n"
        f"{inner}args: {args},\n"
        f"{inner}state: {state},\n"
        f"{inner}streaming: {streaming},\n"
        f"{inner}contentField: {cf},\n"
        f"{inner}waitFor: {wf},\n"
        f"{pad}}}"
    )


def render_registry_to_ts(
    registry: Mapping[str, RenderContract] | None = None,
    *,
    indent: int = 2,
) -> str:
    """Render the contract registry as a deterministic TS literal.

    The output is byte-identical across runs for the same input.
    """
    from lca.infrastructure.tools.contract.render import REGISTRY

    if registry is None:
        registry = REGISTRY

    lines: list[str] = [_HEADER, ""]

    body_pad = " " * indent
    if not registry:
        body = "{}"
    else:
        entries = ",\n".join(
            _ts_contract_entry(name, c, indent + 2) for name, c in sorted(registry.items())
        )
        body = f"{body_pad}{{\n{entries},\n{body_pad}}}"

    lines.append(
        f"export const CONTRACTS: Readonly<Record<string, ToolRenderContract>> = {body} as const;"
    )
    lines.append("")
    return "\n".join(lines)
