"""LCA tool names → LobeHub wire format (``identifier____apiName``).

Backward-compatible re-export — all logic moved to ``lobehub_adapter/`` sub-package.
"""

from __future__ import annotations

# ── Re-export from lobehub_adapter ──────────────────────────
from gateway.lobehub_bridge.lobehub_adapter import (
    CLOUD_SANDBOX_WIRE,
    TOOL_REGISTRY,
    ToolWireSpec,
    build_tool_plugin_state,
    resolve_tool_wire,
    split_wire_name,
    tool_result_content,
    tool_result_preview_limit,
    transform_tool_arguments,
    wire_tool_name,
)

# ── Re-export constants (used by tests and _tool_projection) ─
from gateway.lobehub_bridge.lobehub_adapter.protocol import (
    API_EDIT_FILE,
    API_EXECUTE_CODE,
    API_EXPORT_FILE,
    API_GET_COMMAND_OUTPUT,
    API_GLOB_FILES,
    API_GREP_CONTENT,
    API_KILL_COMMAND,
    API_LIST_FILES,
    API_MOVE_FILES,
    API_READ_FILE,
    API_RUN_COMMAND,
    API_SEARCH_FILES,
    API_WRITE_FILE,
    LOBE_CLOUD_SANDBOX_ID,
    LOBE_LOCAL_SYSTEM_ID,
    LOBE_SKILL_STORE_ID,
    LOBE_SKILLS_ID,
    LOBE_USER_INTERACTION_ID,
    LOBE_WEB_BROWSING_ID,
    PLUGIN_SCHEMA_SEPARATOR,
    SKILL_CONTENT_MAX_LEN,
    SKILL_STORE_API_IMPORT,
    SKILL_STORE_API_IMPORT_MARKET,
    SKILL_STORE_API_SEARCH,
    SKILLS_API_ACTIVATE,
    SKILLS_API_EXEC,
    SKILLS_API_READ_REF,
    TOOL_RESULT_PREVIEW_LIMIT,
    USER_INTERACTION_API_ASK,
    WEB_BROWSING_API_SEARCH,
)

__all__ = [
    "API_EDIT_FILE",
    "API_EXECUTE_CODE",
    "API_EXPORT_FILE",
    "API_GET_COMMAND_OUTPUT",
    "API_GLOB_FILES",
    "API_GREP_CONTENT",
    "API_KILL_COMMAND",
    "API_LIST_FILES",
    "API_MOVE_FILES",
    "API_READ_FILE",
    "API_RUN_COMMAND",
    "API_SEARCH_FILES",
    "API_WRITE_FILE",
    "CLOUD_SANDBOX_WIRE",
    "LOBE_CLOUD_SANDBOX_ID",
    "LOBE_LOCAL_SYSTEM_ID",
    "LOBE_SKILLS_ID",
    "LOBE_SKILL_STORE_ID",
    "LOBE_USER_INTERACTION_ID",
    "LOBE_WEB_BROWSING_ID",
    "PLUGIN_SCHEMA_SEPARATOR",
    "SKILLS_API_ACTIVATE",
    "SKILLS_API_EXEC",
    "SKILLS_API_READ_REF",
    "SKILL_CONTENT_MAX_LEN",
    "SKILL_STORE_API_IMPORT",
    "SKILL_STORE_API_IMPORT_MARKET",
    "SKILL_STORE_API_SEARCH",
    "TOOL_REGISTRY",
    "TOOL_RESULT_PREVIEW_LIMIT",
    "USER_INTERACTION_API_ASK",
    "WEB_BROWSING_API_SEARCH",
    "ToolWireSpec",
    "build_tool_plugin_state",
    "resolve_tool_wire",
    "split_wire_name",
    "tool_result_content",
    "tool_result_preview_limit",
    "transform_tool_arguments",
    "wire_tool_name",
]
